// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6TK53eFnsF1iCo_1Ou0enIs-7KHXVm3I',
    appId: '1:130131121011:web:a7c93dc0e789302db92b06',
    messagingSenderId: '130131121011',
    projectId: 'phat-menghor',
    authDomain: 'phat-menghor.firebaseapp.com',
    storageBucket: 'phat-menghor.appspot.com',
    measurementId: 'G-FHNQSQ55Z9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7pSboErhjmZMrX6nRT4NV80Q8lDNFNBY',
    appId: '1:130131121011:android:673a54781748d1ccb92b06',
    messagingSenderId: '130131121011',
    projectId: 'phat-menghor',
    storageBucket: 'phat-menghor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANPGJaM4yvtsAfh3kGXAdL9efa30Y_QjA',
    appId: '1:130131121011:ios:b10125a42e4ab845b92b06',
    messagingSenderId: '130131121011',
    projectId: 'phat-menghor',
    storageBucket: 'phat-menghor.appspot.com',
    iosClientId: '130131121011-68fm4ooqemsc55b7r9ph6nb9b4nemj29.apps.googleusercontent.com',
    iosBundleId: 'com.example.ass1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANPGJaM4yvtsAfh3kGXAdL9efa30Y_QjA',
    appId: '1:130131121011:ios:b10125a42e4ab845b92b06',
    messagingSenderId: '130131121011',
    projectId: 'phat-menghor',
    storageBucket: 'phat-menghor.appspot.com',
    iosClientId: '130131121011-68fm4ooqemsc55b7r9ph6nb9b4nemj29.apps.googleusercontent.com',
    iosBundleId: 'com.example.ass1',
  );
}
